---
name: flake8-trio CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pyright:
        runs-on: ubuntu-latest
        steps:
            - uses: jakebailey/pyright-action@v1
              #with:
              #    version: 1.1.xxx # Optional (if you want to pin the version)
              #inputs:
              #project: pyproject.toml

    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.11
              uses: actions/setup-python@v3
              with:
                  python-version: '3.11'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools pre-commit
            - name: Run checks
              run: |
                  pre-commit run --all-files

    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.9', '3.10', '3.11']
            fail-fast: false
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools tox
                  python -m tox --notest --recreate -e flake8_5,flake8_6
            - name: Run tests
              run: python -m tox -e flake8_5,flake8_6

                #slow_tests:
                #    runs-on: ubuntu-latest
                #    strategy:
                #        fail-fast: false
                #    steps:
                #        - uses: actions/checkout@v3
                #        - name: Set up Python 3.11
                #          uses: actions/setup-python@v3
                #          with:
                #              python-version: 3.11
                #        - name: Install dependencies
                #          run: |
                #              python -m pip install --upgrade pip setuptools tox
                #              python -m tox --notest --recreate -e flake8_6
                #        - name: Run tests
                #          run: python -m tox -e flake8_6 -- --onlyfuzz --no-cov -n auto

    release:
        runs-on: ubuntu-latest
        needs: [check, test]
        if: github.repository == 'Zac-HD/flake8-trio' &&  github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3
              uses: actions/setup-python@v3
            - name: Install tools
              run: python -m pip install --upgrade build pip setuptools wheel twine gitpython
            - name: Upload new release
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
              run: |
                  python tests/test_changelog_and_version.py --ensure-tag
                  python -m build && twine upload --skip-existing dist/*
